name: Development

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: development

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install Serverless Framework
        run: npm i -g serverless

      - name: Authenticate Serverless with AWS
        run: sls config credentials --provider aws --key ${{ secrets.AWS_KEY }} --secret ${{ secrets.AWS_SECRET }}

      - name: Create .env file
        uses: SpicyPizza/create-envfile@v1
        with:
          NODE_ENV: development
          CONTENTSTACK_API_ENVIRONMENT: ${{ secrets.CONTENTSTACK_API_ENVIRONMENT }}
          CONTENTSTACK_API_KEY: ${{ secrets.CONTENTSTACK_API_KEY }}
          CONTENTSTACK_API_SECRET: ${{ secrets.CONTENTSTACK_API_SECRET }}
          CONTENTSTACK_API_URL: ${{ secrets.CONTENTSTACK_API_URL }}
          ECONOMICS_OBJECT_KEY: ${{ secrets.ECONOMICS_OBJECT_KEY }}
          ECONOMICS_BUCKET_NAME: ${{ secrets.ECONOMICS_BUCKET_NAME }}
          IEX_CLOUD_API_TOKEN: ${{ secrets.IEX_CLOUD_API_TOKEN }}
          IEX_CLOUD_API_URL: ${{ secrets.IEX_CLOUD_API_URL }}
          SITE_URL: ${{ secrets.SITE_URL }}

      - name: Install dependencies
        run: npm i

      - name: Run unit tests
        run: npm run test

      - name: Deploy
        run: sls deploy -s dev